apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: newsman
          artifact-id: 88a9d0bc-7377-4226-bcee-278c844c0d27
          target-environment: ProdEnv